sudo: required

language: php

php:
  - 5.5
  - 5.6

services:
- docker

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
script:
 build/logs/clover.xml && CODECLIMATE_REPO_TOKEN=a2bd599d6b818c89d627730abf660dbb78809acd20f78da3c0b28cfa3493b101 vendor/bin/test-reporter